name: Release jsmuggle

on:
    push:
        tags:
            - 'v*' # Trigger on version tags
    workflow_dispatch:

jobs:
    esbuild:
        name: Create jsmuggle.csj bundle
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install & Build
              run: |
                  npm install
                  npm run build

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2.4.2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: dist/jsmuggle.cjs
                  generate_release_notes: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    seabuild:
        name: Create SEA Binary for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: jsmuggle-linux
                    - os: windows-latest
                      artifact_name: jsmuggle-win.exe
                    - os: macos-latest
                      artifact_name: jsmuggle-macos

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install & Bundle
              run: |
                  npm install
                  npm run build

            - name: Create SEA Binary
              shell: bash
              run: |
                  npm run build:sea
                  chmod +x ./scripts/build-sea.sh
                  ./scripts/build-sea.sh

                  # Rename the output for the release uploader
                  if [ "${{ matrix.os }}" = "windows-latest" ]; then
                      mv dist/jsmuggle.exe dist/${{ matrix.artifact_name }}
                  else
                      mv dist/jsmuggle dist/${{ matrix.artifact_name }}
                  fi

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2.4.2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: dist/${{ matrix.artifact_name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

