name: Release jsmuggle

on:
    push:
        tags:
            - 'v*' # Trigger on version tags
    workflow_dispatch:

jobs:
    esbuild:
        name: Create jsmuggle.csj bundle
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install & Build
              run: |
                  npm install
                  npm run build

            - name: Save bundle
              uses: actions/upload-artifact@v4
              with:
                  name: jsmuggle-bundle
                  path: dist/jsmuggle.cjs

    seabuild:
        needs: esbuild
        name: Create SEA Binary for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: jsmuggle-linux
                    - os: windows-latest
                      artifact_name: jsmuggle-win.exe
                    - os: macos-latest
                      artifact_name: jsmuggle-macos

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Download jsmuggle.cjs
              uses: actions/download-artifact@v4
              with:
                  name: jsmuggle-bundle
                  path: dist

            - name: Create SEA Binary
              shell: bash
              run: |
                  node --experimental-sea-config ./sea-config.json
                  chmod +x ./scripts/build-sea.sh
                  ./scripts/build-sea.sh

                  # Rename the output for the release uploader
                  if [ "${{ matrix.os }}" = "windows-latest" ]; then
                      mv dist/jsmuggle.exe dist/${{ matrix.artifact_name }}
                  else
                      mv dist/jsmuggle dist/${{ matrix.artifact_name }}
                  fi

            - name: Save binary
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.artifact_name }}
                  path: dist/${{ matrix.artifact_name }}

    release:
        needs: [seabuild, esbuild]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: all-binaries
                  merge-multiple: true # Flattens the folder structure

            - name: Create Single Release
              uses: softprops/action-gh-release@v2.4.2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: all-binaries/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
