name: Node.js Package

on:
    push:
        tags:
            - 'v*' # Trigger on version tags
    workflow_dispatch:

jobs:
    esbuild:
        name: esbuild
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install & Build
              run: |
                  npm install
                  npm run build
                  npm run test:run

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2.4.2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: dist/jsmuggle.cjs
                  generate_release_notes: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    seabuild:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: my-tool-linux
                    - os: windows-latest
                      artifact_name: my-tool-win.exe
                    - os: macos-latest
                      artifact_name: my-tool-macos

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.22.0'

            - name: Install & Bundle
              run: |
                  npm install
                  npm run build

            - name: Create SEA Binary
              run: |
                  npm run build:sea

                  cp $(command -v node) "./dist/"
                  # 2. Rename the generic output to your platform name
                  # (Node output name depends on your sea-config.json 'output')
                  mv sea ${{ matrix.artifact_name }} 2>/dev/null || mv sea.exe ${{ matrix.artifact_name }}

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2.4.2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: dist/jsmuggle.cjs
                  generate_release_notes: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
